application: rss-feeder
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /_wave/.*
  script: rss_feeder.py
  
- url: /static
  static_dir: static
  
- url: /update_feed
  script: rss_feeder.py
  login: admin
  
- url: /update_all_feeds
  script: rss_feeder.py
  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico